Feature/yerim 6
potato-club/potato-2team-backend pull request #8
Opened 2021-07-22 10:18 UTC by yerimkoko

테스트 코드는 아직 없습니다 ....

2021-07-22 11:01 UTC, seungh0 requested changes
CI에서 테스트 코드 깨지는데 확인해주세요!

2021-07-22 11:01 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/TokenService.java
> +    private Date EXPIRED_TIME = new Date(System.currentTimeMillis() + 60 * 60 * 24);
지금 이건 상수가 아니라 인스턴스입니다. 컨벤션상 대문자 명시법은 상수에서 사용합니다!

`private static final long  EXPIRED_TIME = 60 * 60 * 24; `
처럼 만료시간 (1일)을 상수로 만들고

아래에서
`.withExpiresAt(<이곳>)  `
이곳에서 현재시간 + EXPIRED_TIME 을 더하는 로직이 더 좋아 보입니다.

2021-07-22 11:01 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/BoardService.java
> +        boardRepository.save(dtoAndMemberIdToEntity.toEntity());
그냥 
`dto.toEntity(memberId)` 하고 BoardCreateRequestDto 에서 처리하면 되지 않나요??
굳이 DTO 하나를 더 만들 필요가 없어보입니다!

2021-07-22 11:01 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/dto/BoardCreateRequestDto.java
>      public Board toEntity() {
여기서 Long memberId를 받아서 처리하면 될거같네여

2021-07-22 11:01 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/TokenService.java
> +    private Date EXPIRED_TIME = new Date(System.currentTimeMillis() + 60 * 60 * 24);
그리고 참고로 이 라이브러리에서 Date를 사용하는지는 모르겠는데

자바쪽에서 제공하는 Date, Calendar 객체들 자바쪽에서 설계 잘못해서 사용안하는걸 권장합니다.

왜냐하면 Date는 불변 객체가 아니여서 멀티쓰레드 환경에서 Thread Safe 하지 않습니다.
그래서 자바8에서 LocalDate or LocalDateTime를 제공하는데 이건 불변객체라서 Thread Safe 해요!

https://madplay.github.io/post/reasons-why-javas-date-and-calendar-was-bad

2021-07-22 11:01 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/TokenService.java
> +            Long memberId = decodedJWT.getClaim("memberId").asLong();
굿@

2021-07-23 00:43 UTC, yerimkoko commented on src/main/java/com/example/potato2teambackend/service/TokenService.java
> +    private Date EXPIRED_TIME = new Date(System.currentTimeMillis() + 60 * 60 * 24);
@seungh0  이 라이브러리에서 Date를 사용하네요 !!!... 상수랑만 분리 하려고 하는데 괜찮은걸까요...?

2021-07-23 00:44 UTC, yerimkoko commented on src/main/java/com/example/potato2teambackend/service/BoardService.java
> +        boardRepository.save(dtoAndMemberIdToEntity.toEntity());
그러게요 .......... 2시간동안 했던 고민입니다 .............. 1초만에 해결이 되네요 ...

2021-07-23 00:44 UTC, yerimkoko commented on src/main/java/com/example/potato2teambackend/dto/BoardCreateRequestDto.java
>      public Board toEntity() {
ㅠㅠㅠㅠㅠㅠㅠㅠ

2021-07-23 02:46 UTC, merged

2021-07-23 18:09 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/TokenService.java
> +    private Date EXPIRED_TIME = new Date(System.currentTimeMillis() + 60 * 60 * 24);
알림이 왜 안오죵..

라이브러리 측에서 Date만 제공한다면 어쩔수 없졍

2021-07-23 18:09 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/BoardService.java
> +        boardRepository.save(dtoAndMemberIdToEntity.toEntity());
ㅎㅎㅎㅎㅎ

2021-07-23 18:16 UTC, seungh0 commented on src/main/java/com/example/potato2teambackend/service/TokenService.java
> +    private Date EXPIRED_TIME = new Date(System.currentTimeMillis() + 60 * 60 * 24);
그러네영.. 지금 3.x.x 버전인데
4.x.x 부터 쓸 수 있다네영..

https://github.com/auth0/java-jwt/issues/250